apiVersion: v1
kind: Service
metadata:
    name: "user-interface"
    labels:
        app: "user-interface"
spec:
    type: LoadBalancer
    ports:
    - port: 90
      targetPort: 90
      protocol: TCP
      name: http
    selector:
        app: "user-interface"