apiVersion: v1
kind: Service
metadata:
    name: "rpsbattle-9d68"
    labels:
        app: "rpsbattle-9d68"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "rpsbattle-9d68"